@restaurant1=dab961f7-5441-4827-a55e-7fcbc86a8fb2
@resto1dish1=27756a48-0b85-4499-aadb-c08a97943263
@resto1dish2=6c273939-faf5-4eca-988d-08b14533849e
@resto1dish3= 98be5020-eb67-49e0-815e-3b2f7e1808e0
@owner1=803afbdd-a7dc-4735-bbf4-526d99cbf686
@owner1username=linguinealfredo
@owner1password=owner
@owner2=82090ea4-05d5-4d95-97de-e33760ac73f9
@owner2username=shigerumiyamoto
@owner2password=owner
@owner3=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
@owner3username=jamesgarfield
@owner3password=owner
@owner4=82090ea4-05d5-4d95-97de-e33760ac2468
@owner4username=remcomeert
@owner4password=owner

@order1=550e8400-e29b-41d4-a716-446655440000

@grill=11111111-2222-3333-4444-555555555555
@myorder=ab6e2a26-1e7f-4827-a8ea-6c16f4852e9b

### Get access token for owner1
POST http://localhost:8180/realms/keepdishesgoing/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=keepdishesgoing&client_secret=GXg3zjaA8qrRFWFU06yhLrvLVI877xYE&username={{owner1username}}&password={{owner1password}}&grant_type=password&scope=openid

> {%
    client.global.set("session_token", response.body.access_token);
%}

### Get access token for owner2
POST http://localhost:8180/realms/keepdishesgoing/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=keepdishesgoing&client_secret=GXg3zjaA8qrRFWFU06yhLrvLVI877xYE&username={{owner2username}}&password={{owner2password}}&grant_type=password&scope=openid

> {%
    client.global.set("session_token", response.body.access_token);
%}

### Get access token for owner3, grill owner
POST http://localhost:8180/realms/keepdishesgoing/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=keepdishesgoing&client_secret=GXg3zjaA8qrRFWFU06yhLrvLVI877xYE&username={{owner3username}}&password={{owner3password}}&grant_type=password&scope=openid

> {%
    client.global.set("session_token", response.body.access_token);
%}

### Get access token for owner4, no restaurant yet
POST http://localhost:8180/realms/keepdishesgoing/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=keepdishesgoing&client_secret=GXg3zjaA8qrRFWFU06yhLrvLVI877xYE&username={{owner4username}}&password={{owner4password}}&grant_type=password&scope=openid

> {%
    client.global.set("session_token", response.body.access_token);
%}

### Create a new restaurant
POST http://localhost:8081/api/restaurants
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "name": "Lekker eten",
  "address": {
    "street": "meir",
    "number": 16,
    "postalCode": 2000,
    "country": "belgium"
  },
  "type": "AMERICAN",
  "openingHours": [
    {
      "day": "MONDAY",
      "openingTime": "08:00:00",
      "closingTime": "21:00:00"
    },
    {
      "day": "TUESDAY",
      "openingTime": "08:00:00",
      "closingTime": "21:00:00"
    },
    {
      "day": "WEDNESDAY",
      "openingTime": "08:00:00",
      "closingTime": "21:00:00"
    },
    {
      "day": "THURSDAY",
      "openingTime": "08:00:00",
      "closingTime": "21:00:00"
    },
    {
      "day": "FRIDAY",
      "openingTime": "08:00:00",
      "closingTime": "21:00:00"
    },
    {
      "day": "SATURDAY",
      "openingTime": "08:00:00",
      "closingTime": "21:00:00"
    }
  ],
  "logo": "2025-09-30T152345.png",
  "contactEmail": "lekker.eten@student.kdg.be"
}

### Get all restaurants
GET http://localhost:8081/api/restaurants

### Get all restaurants
GET http://localhost:8081/api/restaurants/mine
Authorization: Bearer {{session_token}}

### Get a specific restaurant by ID
GET http://localhost:8081/api/restaurants/{{restaurant1}}

### Get the public menu of a restaurant
GET http://localhost:8081/api/restaurants/{{restaurant1}}/menu

### Get the full menu of a restaurant
GET http://localhost:8081/api/restaurants/{{restaurant1}}/menu_full
Authorization: Bearer {{session_token}}

### Create a new dish for a restaurant
POST http://localhost:8081/api/restaurants/{{restaurant1}}/menu
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "name": "Lasagne",
  "description": "Garfield's favorite",
  "price": 44.99,
  "state": "NOT_AVAILABLE"
}

### Get a specific dish from a restaurant
GET http://localhost:8081/api/restaurants/{{restaurant1}}/menu/{{resto1dish1}}
Authorization: Bearer {{session_token}}

### Update a dish's state
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/menu/{{resto1dish3}}/state
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "state": "PUBLISHED"
}

### Open or close a restaurant
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}?open=true
Authorization: Bearer {{session_token}}
Content-Type: application/json

### Reset overwrite opening hours
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/resetOverwrite
Authorization: Bearer {{session_token}}
Content-Type: application/json

### Update a dish (name & description)
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/menu/{{resto1dish2}}
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "name": "Updated Fettuccine Alfredo",
  "description": "Freshly made creamy Alfredo sauce with herbs"
}

### Update dish1's state to ready for publishing (prep)
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/menu/{{resto1dish1}}/state
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "state": "READY_FOR_PUBLISHING"
}

### Update dish2's state to ready for publishing (prep)
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/menu/{{resto1dish2}}/state
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "state": "READY_FOR_PUBLISHING"
}

### Publish all ready dishes
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/menu/publish_ready
Authorization: Bearer {{session_token}}
Content-Type: application/json

### Update dish2's state to ready for publishing
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/menu/{{resto1dish2}}/state
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "state": "READY_FOR_PUBLISHING"
}

### Schedule dishes for future publishing
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/menu/publish_schedule
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "scheduledDate": "2025-10-28T18:07:00+01:00",
  "dishIds": [
    "{{resto1dish2}}",
    "{{resto1dish3}}"
  ]
}

### GET all pending
GET http://localhost:8081/api/restaurants/{{restaurant1}}/orders_pending
Authorization: Bearer {{session_token}}

### Accept a pending order
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/orders/{{order1}}/accept
Authorization: Bearer {{session_token}}

### Reject a pending order
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/orders/{{order1}}/reject
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
  "reason": "You made a bad order."
}

### Ready an accepted order
PATCH http://localhost:8081/api/restaurants/{{restaurant1}}/orders/{{order1}}/ready
Authorization: Bearer {{session_token}}